config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :warehouses do
    resources :stock_product_destinations, only: %i[create]
  end

  resources :suppliers
  resources :product_models

  resources :orders do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member

    resources :order_items, only: %i[new create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[index show create]
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier

  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, :weight, :width, :height, :depth, :sku, :supplier_id, presence: true
  validates :sku, uniqueness: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :set_product_model, only: %i[show]
  before_action :authenticate_user!, only: %i[index]

  def index
    @product_models = ProductModel.all
  end

  def show
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    @product_model = ProductModel.new(product_model_params)

    if @product_model.save
      redirect_to @product_model, notice: t('notices.product_model.registered')
    else
      @suppliers = Supplier.all
      flash.now.alert = t('alerts.product_model.register_fail')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_product_model
    @product_model = ProductModel.find(params[:id])
  end

  def product_model_params
    params.require(:product_model).permit(:name, :weight, :width, :height, :depth, :sku, :supplier_id)
  end
end

app/views/product_models/_form.html.erb
<div class='form-container'>
  <%= form_with model: @product_model do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= error_message_for(@product_model, :name) %>
    </div>
    <div>
      <%= f.label :weight %>
      <%= f.text_field :weight %>
      <%= error_message_for(@product_model, :weight) %>
    </div>
    <div>
      <%= f.label :width %>
      <%= f.text_field :width %>
      <%= error_message_for(@product_model, :width) %>
    </div>    
    <div>
      <%= f.label :height %>
      <%= f.text_field :height %>
      <%= error_message_for(@product_model, :height) %>
    </div>
    <div>
      <%= f.label :depth %>
      <%= f.text_field :depth %>
      <%= error_message_for(@product_model, :depth) %>
    </div>
    <div>
      <%= f.label :sku %>
      <%= f.text_field :sku %>
      <%= error_message_for(@product_model, :sku) %>
    </div>
    <div>
      <%= f.label :supplier_id %>
      <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
      <%= error_message_for(@product_model, :supplier_id) %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/product_models/index.html.erb
<h2><%= ProductModel.model_name.human(count: 2) %></h2>

<div class='new-button'><%= link_to t('views.register_product_model'), new_product_model_path %></div>

<% if @product_models.any? %>
  <table>
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.product_model.name') %></th>
        <th><%= t('activerecord.attributes.product_model.sku') %></th>
        <th><%= t('activerecord.attributes.supplier.brand_name') %></th>
      </tr>
    </thead>
    <tbody>
      <% @product_models.each do |product_model| %>
      <tr>
        <td><%= link_to product_model.name, product_model %></td>
        <td><%= product_model.sku %></td>
        <td><%= product_model.supplier.brand_name %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class='no-data'>There are no registered product models!</p>
<% end %>

app/views/product_models/new.html.erb
<h2><%= t('views.register_product_model') %></h2>

<%= render 'form' %>

app/views/product_models/show.html.erb
<h2><%= ProductModel.model_name.human(count: 1) %> <span class="highlight"><%= @product_model.name %></span></h2>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.product_model.weight') %></th>
      <th><%= t('views.dimension') %></th>
      <th><%= t('activerecord.attributes.product_model.sku') %></th>
      <th><%= t('activerecord.attributes.product_model.supplier_id') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @product_model.weight %>g</td>
      <td><%= @product_model.width %>cm x <%= @product_model.height %>cm x <%= @product_model.depth %>cm</td>
      <td><%= @product_model.sku %></td>
      <td><%= @product_model.supplier.brand_name %></td>
    </tr>
  </tbody>
</table>