config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :warehouses do
    resources :stock_product_destinations, only: %i[create]
  end

  resources :suppliers
  resources :product_models

  resources :orders do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member

    resources :order_items, only: %i[new create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[index show create]
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user

  has_many :order_items
  has_many :product_models, through: :order_items

  validates :warehouse_id, :supplier_id, :code, :expected_delivery_date, presence: true
  validate :expected_delivery_date_future_validation

  before_validation :generate_code, on: :create

  enum status: { pending: 0, delivered: 1, canceled: 2 }

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(10).upcase
  end

  def expected_delivery_date_future_validation
    if self.expected_delivery_date.present? && self.expected_delivery_date <= Date.today
      self.errors.add(:expected_delivery_date, 'must be in the future')
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order_and_check_user, only: %i[show edit update delivered canceled]
  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def show
  end

  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    @order = Order.new(orders_params)
    @order.user = current_user

    if @order.save
      redirect_to @order, notice: t('notices.order.registered')
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now.alert = t('alerts.order.register_fail')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def update
    if @order.update(orders_params)
      redirect_to @order, notice: t('notices.order.updated')
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now.alert = t('alerts.order.update_fail')
      render :edit, status: :unprocessable_entity
    end
  end

  def search
    @code = params['query']
    @orders = Order.where("code LIKE ?", "%#{@code}%")
  end

  def delivered
    @order.delivered!

    @order.order_items.each do |item|
      item.quantity.times do
        StockProduct.create!(order: @order, product_model: item.product_model, warehouse: @order.warehouse)
      end
    end

    redirect_to @order
  end

  def canceled
    @order.canceled!
    redirect_to @order
  end

  private

  def orders_params
    params.require(:order).permit(:warehouse_id, :supplier_id, :expected_delivery_date, :status)
  end

  def set_order_and_check_user
    @order = Order.find(params[:id])

    if @order.user != current_user
      return redirect_to orders_path, alert: 'You do not have access to this order'
    end
  end
end

app/views/orders/_form.html.erb
<div class='form-container'>
  <%= form_with model: @order do |f| %>
    <div>
      <%= f.label :warehouse_id %>
      <%= f.collection_select :warehouse_id, @warehouses, :id, :warehouse_info %>
      <%= error_message_for(@order, :warehouse_id) %>
    </div>
    <div>
      <%= f.label :supplier_id %>
      <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
      <%= error_message_for(@order, :supplier_id) %>
    </div>
    <div>
      <%= f.label :expected_delivery_date %>
      <%= f.date_field :expected_delivery_date %>
      <%= error_message_for(@order, :expected_delivery_date) %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/orders/edit.html.erb
<h2><%= t('actions.edit') %> <%= @order.code %></h2>

<%= render 'form' %>

app/views/orders/index.html.erb
<h2><%= Order.model_name.human(count: 2) %></h2>

<div class='new-button'><%= link_to t('views.register_order'), new_order_path %></div>

<% if @orders.any? %>
 <table>
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.order.code') %></th>
        <th><%= t('views.responsible') %></th>
        <th><%= t('activerecord.attributes.order.warehouse_id') %></th>
        <th><%= Supplier.model_name.human(count: 1) %></th>
        <th><%= t('activerecord.attributes.order.expected_delivery_date') %></th>
        <th><%= t('activerecord.attributes.order.status') %></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.code, order %></td>
          <td><%= order.user.name %> - <%= order.user.email %></td>
          <td><%= order.warehouse.warehouse_info %></td>
          <td><%= order.supplier.corporate_name %></td>
          <td><%= I18n.localize(order.expected_delivery_date) %></td>
          <td><%= t("status.#{order.status}") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class='no-data'>There are no registered orders!</p>
<% end %>

app/views/orders/new.html.erb
<h2><%= t('views.register_order') %></h2>

<%= render 'form' %>

app/views/orders/search.html.erb
<h2>Search results for <%= @code %></h2>

<p class='count'><%= t('views.found', count: @orders.count) %></p>

<% if @orders.any? %>
  <table>
    <thead>
      <tr>
        <th>Code</th>
        <th>Responsible User</th>
        <th><%= t('views.warehouse_id') %></th>
        <th><%= t('models.supplier') %></th>
        <th><%= t('attributes.order.expected_delivery_date') %></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.code %></td>
          <td><%= order.user.name %> - <%= order.user.email %></td>
          <td><%= order.warehouse.warehouse_info %></td>
          <td><%= order.supplier.corporate_name %></td>
          <td><%= I18n.localize(order.expected_delivery_date) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No order found</p>
<% end %>

app/views/orders/show.html.erb
<h2><%= Order.model_name.human(count: 1) %> <span class="highlight"><%= @order.code %></span></h2>

<table>
  <thead>
    <tr>
      <th><%= t('views.responsible') %></th>
      <th><%= t('activerecord.attributes.order.warehouse_id') %></th>
      <th><%= Supplier.model_name.human(count: 1) %></th>
      <th><%= t('activerecord.attributes.order.expected_delivery_date') %></th>
      <th><%= t('activerecord.attributes.order.status') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @order.user.name %> - <%= @order.user.email %></td>
      <td><%= @order.warehouse.warehouse_info %></td>
      <td><%= @order.supplier.corporate_name %></td>
      <td><%= l(@order.expected_delivery_date) %></td>
      <td><%= t("status.#{@order.status}") %></td>
    </tr>
  </tbody>
</table>

<div class='action-button'>
  <div class='edit'><%= link_to t('actions.edit'), edit_order_path(@order) %></div>

  <% if @order.pending? %>
    <div class='delivered'><%= button_to t('actions.delivered'), delivered_order_path(@order) %></div>
    <div class='canceled'><%= button_to t('actions.canceled'), canceled_order_path(@order) %></div>
  <% end %>
</div>

<h2><%= OrderItem.model_name.human %></h2>

<table>
  <thead>
    <tr>
      <th><%= ProductModel.model_name.human %></th>
      <th><%= Order.model_name.human %></th>
      <th><%= t('activerecord.attributes.order_item.quantity') %></th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_items.each do |item| %>
      <tr>
        <td><%= item.product_model.name %></td>
        <td><%= item.order.code %></td>
        <td><%= item.quantity %></td>
      </tr>
    <% end %> 
  </tbody>
</table>

<div class='action-button'>
  <div class='add-item'><%= link_to t('actions.add_item'), new_order_order_item_path(order_id: @order.id) %></div>
</div>