config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :warehouses do
    resources :stock_product_destinations, only: %i[create]
  end

  resources :suppliers
  resources :product_models

  resources :orders do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member

    resources :order_items, only: %i[new create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[index show create]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models

  validates :corporate_name, :brand_name, :registration_number, :address, :city, :state, :email, presence: true
  validates :corporate_name, uniqueness: true
  validates :registration_number, uniqueness: true
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[show edit update destroy]

  def index
    @suppliers = Supplier.all
  end

  def show
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to suppliers_path, notice: t('notices.supplier.registered')
    else
      flash.now.alert = t('alerts.supplier.register_fail')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: t('notices.supplier.updated')
    else
      flash.now.alert = t('alerts.supplier.update_fail')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @supplier.destroy
    redirect_to suppliers_path, notice: t('notices.supplier.deleted')
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :address, :city, :state, :email)
  end
end

app/views/suppliers/_form.html.erb
<div class='form-container'>
  <%= form_with model: @supplier do |f| %>
    <div>
      <%= f.label :corporate_name %>
      <%= f.text_field :corporate_name %>
      <%= error_message_for(@supplier, :corporate_name) %>
    </div>
    <div>
      <%= f.label :brand_name %>
      <%= f.text_field :brand_name %>
      <%= error_message_for(@supplier, :brand_name) %>
    </div>
    <div>
      <%= f.label :registration_number %>
      <%= f.text_field :registration_number %>
      <%= error_message_for(@supplier, :registration_number) %>
    </div>    
    <div>
      <%= f.label :address %>
      <%= f.text_field :address %>
      <%= error_message_for(@supplier, :address) %>
    </div>
    <div>
      <%= f.label :city %>
      <%= f.text_field :city %>
      <%= error_message_for(@supplier, :city) %>
    </div>
    <div>
      <%= f.label :state %>
      <%= f.text_field :state %>
      <%= error_message_for(@supplier, :state) %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= error_message_for(@supplier, :email) %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/suppliers/edit.html.erb
<h2><%= t('actions.edit') %> <%= @supplier.brand_name %></h2>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h2><%= Supplier.model_name.human(count: 2) %></h2>

<section class='suppliers'>
  <div class='new-button'><%= link_to t('views.register_supplier'), new_supplier_path %></div>
  
  <% if @suppliers.any? %>
    <table>
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.supplier.brand_name') %></th>
          <th><%= t('views.location') %></th>
        </tr>
      </thead>
      <tbody>
        <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= link_to supplier.brand_name , supplier %></td>
          <td><%= supplier.city %> - <%= supplier.state %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class='no-data'>There are no registered suppliers!</p>
  <% end %>
</section>

app/views/suppliers/new.html.erb
<h2><%= t('views.register_supplier') %></h2>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h2><%= Supplier.model_name.human(count: 1) %> <span class="highlight"><%= @supplier.brand_name %></span></h2>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.supplier.corporate_name') %></th>
      <th><%= t('activerecord.attributes.supplier.registration_number') %></th>
      <th><%= t('views.location') %></th>
      <th><%= t('activerecord.attributes.supplier.email') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @supplier.corporate_name %></td>
      <td><%= @supplier.registration_number %></td>
      <td><%= @supplier.address %> - <%= @supplier.city %> - <%= @supplier.state %></td>
      <td><%= @supplier.email %></td>
    </tr>
  </tbody>
</table>

<div class='action-button'>
  <div class='edit'><%= link_to t('actions.edit'), edit_supplier_path(@supplier) %></div>
  <div class='delete'><%= button_to t('actions.delete'), supplier_path(@supplier), method: :delete, form: { data: { turbo_confirm: t('views.are_you_sure') } } %></div>
</div>