config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :warehouses do
    resources :stock_product_destinations, only: %i[create]
  end

  resources :suppliers
  resources :product_models

  resources :orders do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member

    resources :order_items, only: %i[new create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[index show create]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1><%= image_tag 'warehouse-solid', class: 'icon' %>Warehouses & Stocks</h1>
    </header>    

    <nav>
      <ul>
        <li><%= link_to t('views.home'), root_path %></li>
        <li><%= link_to Supplier.model_name.human(count: 2), suppliers_path %></li>
        <li><%= link_to ProductModel.model_name.human(count: 2), product_models_path %></li>
        <li><%= link_to Order.model_name.human(count: 2), orders_path %></li>

        <% if user_signed_in? %>
          <li>
            <%= form_with url: search_orders_path, method: :get do |f| %>
              <%= f.label :query, t('views.search_order') %>
              <%= f.text_field :query, placeholder: t('views.search_order') %>
              <%= f.submit t('views.search') %>
            <% end %>
          </li>

          <div class='user'>
            <li><%= current_user.user_info %></li>
            <li><%= button_to t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete %></li>
          </div>
        <% else %>
          <div class='user'>
            <li><%= link_to t('devise.sessions.sign_in'), new_user_session_path %></li>
          </div>
        <% end %>

        <li><%= link_to t('views.english'), url_for(locale: 'en') %></li>
        <li><%= link_to t('views.portuguese'), url_for(locale: 'pt-BR') %></li>
      </ul>
    </nav>    
    
    <main>
      <% if notice.present? || alert.present? %>
        <div class="<%= notice.present? ? 'success-message' : 'error-message' %>">
          <%= notice || alert %>
        </div>
      <% end %>      

      <%= yield %>
    </main>    
  </body>
</html>